### ISSUE TITLE
Automatic launch at startup

### ISSUE THREAD

**Issue by MikeDvorsky** [CentralIllinoisRoboticsClub/wheele#18]
Currently we need to connect to WheelE over wifi and start the launch file.  It would be convenient if this were automatic.  This would be best if combined with a user interface to start/stop, an efficient way to enter waypoints, etc.

**Comment by mattp256** [comment]
It looks like there are 3 convenient ways to launch processes automatically at startup: rc.local, systemd, and cron. Reference: [https://www.raspberrypi.org/documentation/linux/usage/rc-local.md](url)

rc.local seems to be the least reliable according to the reference article, so I'd lean towards systemd or cron. Either should work but systemd is probably the most logical choice in this case since it's specifically geared towards starting/stopping services, as opposed to periodic job execution by cron. It's worth a shot.

A couple references on systemd startup scripts:
https://www.raspberrypi.org/documentation/linux/usage/systemd.md
https://blog.roverrobotics.com/how-to-run-ros-on-startup-bootup/

By the way, what Linux distro is running on the Wheele pi? Raspbian? Ubuntu?

**Comment by MikeDvorsky** [comment]
The WheelE Pi uses Ubuntu.  I am pretty sure the version is 16.04.

Thanks for researching this.  I agree that systemd looks like the best method.

**Comment by mattp256** [comment]
Noting this down for future reference...
Manual for systemd service file syntax: https://www.man7.org/linux/man-pages/man7/systemd.syntax.7.html
From there follow links to systemd.unit(5) and systemd.service(5)
