### ISSUE TITLE
User interface for control (display, touchscreen/buttons, sound effects, etc.)

### ISSUE THREAD

**Issue by MikeDvorsky** [CentralIllinoisRoboticsClub/wheele#19]

**Comment by mattp256** [comment]
I'm interested in taking this up - assigned myself to the issue after confirming with Mike and Karl at the November 2020 build session. Two related issues are #15 for a safe shutdown button, and #18 for automatic launch at startup - I also signed up for those issues.

Planning to start by looking at a Nextion "Basic Series" display. Mike has seen some recent articles that make this display look promising, and he has one available if needed (3.5"). We talked about a couple options for how the display would communicate with wheele's raspberry pi, either a) directly via synchronous or asynchronous serial like like SPI/I2C, or b) serial link to one of wheele's arduinos which would then translate to CAN for transmission to the pi. If not a touchscreen, we also considered starting very simple with one or two mechanical buttons that could trigger some action in the pi (i.e. safe shutdown of the robot/OS).

**Comment by mattp256** [comment]
Another interesting option for a touchscreen, $40 from Adafruit: https://cdn-learn.adafruit.com/downloads/pdf/adafruit-3-5-color-320x480-tft-touchscreen-breakout.pdf.  SPI interface, libraries and examples available for interfacing with both arduino and linux/raspberry pi.

**Comment by MikeDvorsky** [comment]
In looking for info on the Nextion display, I found one of the best put downs ever.  Someone described the editor as looking like it was "designed by a committee that only meets on Friday afternoons."  Love it.

My problem with the Adafruit display for WheelE is twofold.  First, the SPI peripheral on the RPi is occupied with the CAN controller.  Second, it looks like the RPi (or arduino) needs to do all of the pixel writing over SPI, and needs to use analog inputs to read and interpret the touchscreen.

Even though the Nextion is not as capable as I suggested last night, it does manage those basic functions internally.  The serial messages to/from the display are communication with the high-level graphical widgets rather than low-level pixel drawing and touchscreen reading.

By the way, this is the exact Nextion kit I ordered:
https://www.amazon.com/NX4832T035-Resistive-Enclosure-Transparent-Raspberry/dp/B08535Y1XW/ref=sr_1_4?crid=2REB58GMXZTXI&dchild=1&keywords=nextion+3.5&qid=1605750104&sprefix=nextion%2Caps%2C188&sr=8-4

**Comment by mattp256** [comment]
_Designed by committee that only meets on Friday afternoons_ - ouch! Actually the editor is my biggest hang-up with Nextion too. First, only runs on Windows (unless you do some virtual machine or WINE solution...<eye roll...>)- a problem for me because I don't have a Windows machine anymore. I suspect others that are or may become involved with programming for CIRC may face the same problem. Second, even if you get past Windows, it requires learning the editor GUI and the whole process for transferring the program to the display - not a deal breaker but I bet it would be easier to get people engaged with a technology they are already familiar with, or at least that has wide application (i.e. arduino or python). I also think maintenance and upgrades would be easier using git and source code over a Nextion editor project file.

I do agree it's nice that the Nextion display integrates drawing and touchscreen control - haven't found any reasonably priced alternatives that do that, BUT the drawbacks with the editor are enough to make me stop and think. What about adding another small arduino to wheele, dedicated to touchscreen control? Basically make our own programmable display, but using a more widely adopted toolchain? Wire up the arduino to the adafruit board, drop it in an enclosure, feed out SPI or I2C lines, or even CAN if we also wire up a converter to this new arduino?

**Comment by MikeDvorsky** [comment]
I have absolutely no objection to the proposal to make our own programmable display based on a (presumably low-cost) TFT touchscreen and an arduino (or other low-cost controller).  The development sounds like fun, and this is a hobby after all, so it should be fun.

**Comment by MikeDvorsky** [comment]
If you google "stm32 discovery touch screen", it will turn up several stm32 dev kits with touch screen interfaces that might be nice for this purpose at reasonable prices ($50 or $60 range).  Many programming options, so I am sure they are not tied to Windows.

**Comment by mattp256** [comment]
I got myself into trouble over the weekend because it hit me that I may actually have an old arduino in my junk box. Turns out that I do (Digilent chipKIT Max32) and it still works. Between adafruit and a couple other references I got a simple menu system coded up in pretty short order, compiled and downloaded to the board. Adafruit has graphics driver libs that are easy to work with. Problem is I don't have a display to really test it (boo) But, I should have one in a few days (yay) 3.2" TFT LCD + resistive touchscreen & microSD socket (https://www.adafruit.com/product/1743) 

My plan is to put it through some paces to see if it could be viable for WheelE. If I get it soon enough I can run it by the club at the next meeting for feedback. Should be fun to play with even if we don't end up using it.

**Comment by coderkarl** [comment]
Did you see the M5Stack products at adafruit?
https://www.adafruit.com/product/4176
https://www.adafruit.com/product/4178
The simplest would be just the 4178 with the non-touch screen and 3 buttons ready to go. I'm not sure how customizable the screen and buttons are yet.

**Comment by mattp256** [comment]
I have not seen the M5Stack before. Definitely looks good for mobile, hand-held type use. The featherboard touchscreen looks very similar to the one I got to play with, just a bit smaller. I bet they would both work with feathers in SPI mode. I'm finding it pretty easy to use, so would lean that direction. Only question with the feather is does it have enough I/O to handle the touch display and communicate with the pi?

**Comment by maximus5684** [comment]
Closed by CentralIllinoisRoboticsClub/wheele_gui#1.
